export const departments = [
  {
    slug: 'cse',
    name: 'Computer Science & Engineering',
    tagline: 'Innovating the future with technology',
    shortDesc: 'Blend of core computing, AI, and software development to shape future technologists.',
    highlights: ['AI', 'Cloud', 'Cyber Security'],
    image: "/departments/cse.jpeg",
    banner:"/departments/csebanner.jpeg",
    overview: 'The Department of CSE at SJBIT offers a cutting-edge curriculum focused on software development, data structures, AI, and emerging technologies, equipping students with both theoretical knowledge and practical skills.',
    keyAreas: ['Artificial Intelligence', 'Machine Learning', 'Cloud Computing', 'Cyber Security', 'Data Science'],
    facilities: ['Advanced Programming Lab', 'AI & ML Research Center', 'IoT Lab', 'High-Performance Computing Cluster'],
    faculty: 'PhD faculty from premier institutes, actively publishing research and mentoring innovative student projects.',
    placements: { percent: '92%', recruiters: ['Infosys', 'TCS', 'Wipro', 'Accenture', 'Amazon'] },
    careers: ['Software Engineer', 'AI Engineer', 'Data Scientist', 'Cloud Architect', 'Cyber Security Analyst'],
    stats: { intake: 180, placement: '92%', labs: 12, years: 25 },
  },
  {
    slug: 'ise',
    name: 'Information Science & Engineering',
    banner:"/departments/isebanner.jpeg",
    tagline: 'Bridging data and innovation',
    shortDesc: 'Focus on information systems, data analytics, and enterprise solutions for the digital era.',
    highlights: ['Big Data', 'Analytics', 'Web Tech'],
    image: "/departments/ise.jpeg",
    overview: 'ISE emphasizes information processing, database management, and modern web technologies.',
    keyAreas: ['Database Systems', 'Web Development', 'Big Data Analytics', 'Information Security'],
    facilities: ['Data Analytics Lab', 'Web Technology Lab', 'Network Security Lab'],
    faculty: 'Industry-experienced faculty specializing in analytics and enterprise IT.',
    placements: { percent: '89%', recruiters: ['TCS', 'Cognizant', 'Capgemini', 'IBM'] },
    careers: ['Data Analyst', 'Web Developer', 'System Analyst', 'IT Consultant'],
    stats: { intake: 120, placement: '89%', labs: 8, years: 20 },
  },
  {
    slug: 'ece',
    name: 'Electronics & Communication Engineering',
    tagline: 'Connecting the world through innovation',
    highlights: ['VLSI', 'Embedded', 'IoT'],
    image: "/departments/ece.jpeg",
    banner:"/departments/ecebanner.jpeg",
    shortDesc: 'Core electronics, VLSI, embedded systems, and communication technologies.',
    overview: 'ECE provides a strong foundation in electronics, communication, and embedded intelligent systems.',
    keyAreas: ['VLSI Design', 'Embedded Systems', 'Signal Processing', 'IoT'],
    facilities: ['VLSI Lab', 'Communication Lab', 'Embedded Systems Lab'],
    faculty: 'Experts in electronics with active research in IoT and communication.',
    placements: { percent: '85%', recruiters: ['Texas Instruments', 'Siemens', 'Bosch', 'Wipro'] },
    careers: ['Embedded Engineer', 'VLSI Designer', 'Network Engineer', 'IoT Developer'],
    stats: { intake: 180, placement: '85%', labs: 10, years: 22 },
  },
  {
    slug: 'mechanical',
    name: 'Mechanical Engineering',
    tagline: 'Engineering machines that move the world',
    highlights: ['Robotics', 'Design', 'Manufacturing'],
    image: "/departments/mech.jpeg",
    banner:"/departments/mechbanner.jpeg",
    shortDesc: 'Design, manufacturing, robotics, and thermal engineering excellence.',
    overview: 'Focus on CAD/CAM, robotics, and advanced manufacturing technologies.',
    keyAreas: ['Robotics', 'CAD/CAM', 'Thermal Engineering', 'Automotive'],
    facilities: ['CNC Lab', 'Robotics Lab', '3D Printing Facility', 'Thermal Lab'],
    faculty: 'Faculty with industry experience in manufacturing and automotive design.',
    placements: { percent: '80%', recruiters: ['Tata Motors', 'L&T', 'Ashok Leyland', 'Bosch'] },
    careers: ['Design Engineer', 'Manufacturing Engineer', 'Robotics Engineer'],
    stats: { intake: 180, placement: '80%', labs: 14, years: 28 },
  },
  {
    slug: 'civil',
    name: 'Civil Engineering',
    tagline: 'Building the foundations of tomorrow',
    highlights: ['Structures', 'Surveying', 'Sustainability'],
    image: "/departments/civil.jpeg",
    banner:"/departments/civilbanner.jpeg",
    shortDesc: 'Infrastructure, structural design, and sustainable construction.',
    overview: 'Emphasis on sustainable infrastructure and smart city technologies.',
    keyAreas: ['Structural Engineering', 'Geotechnical', 'Environmental', 'Smart Cities'],
    facilities: ['Material Testing Lab', 'Survey Lab', 'Structural Analysis Lab'],
    faculty: 'Experienced faculty with field and research expertise.',
    placements: { percent: '78%', recruiters: ['L&T', 'Shapoorji', 'Sobha', 'ACC'] },
    careers: ['Structural Engineer', 'Site Engineer', 'Urban Planner'],
    stats: { intake: 120, placement: '78%', labs: 9, years: 24 },
  },
  {
    slug: 'ai-ml',
    name: 'Artificial Intelligence & Machine Learning',
    tagline: 'Shaping intelligence, powering tomorrow',
    highlights: ['Deep Learning', 'NLP', 'Computer Vision'],
    image: "/departments/ai-ml.jpeg",
    banner:"/departments/aimlbanner.jpeg",
    shortDesc: 'Specialized program in AI, ML, deep learning, and data-driven innovation.',
    overview: 'Dedicated to cutting-edge AI research and real-world applications.',
    keyAreas: ['Deep Learning', 'NLP', 'Computer Vision', 'Reinforcement Learning'],
    facilities: ['AI Supercomputing Lab', 'Deep Learning Workstations', 'Research Incubation Center'],
    faculty: 'PhD faculty with AI research collaborations.',
    placements: { percent: '90%', recruiters: ['Amazon', 'Microsoft', 'NVIDIA', 'Accenture AI'] },
    careers: ['AI Engineer', 'ML Engineer', 'Data Scientist', 'Research Scientist'],
    stats: { intake: 60, placement: '90%', labs: 6, years: 5 },
  },
];